export const MAKE_SEARCH = 'MAKE_SEARCH';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const SET_USER_WISH_LIST = 'SET_USER_WISH_LIST';


